# Generated by Django 5.0.1 on 2024-01-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('countries', '0004_rename_countries_risk_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
            preserve_default=False,
        ),
    ]
