# Generated by Django 5.0.1 on 2024-01-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('label', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='countries',
            field=models.ManyToManyField(to='countries.country'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.risklevel'),
            preserve_default=False,
        ),
    ]
