# Generated by Django 5.0.1 on 2024-01-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_risklevel_risk_countries_risk_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='countries',
        ),
        migrations.AddField(
            model_name='risk',
            name='countries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
            preserve_default=False,
        ),
    ]
