# Generated by Django 5.0.1 on 2024-01-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_remove_risk_countries_risk_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='countries',
            new_name='country',
        ),
    ]
